#define CONSOLE_CMD
#define CONSOLE_VESAFB
#define DOWNLOAD_PROTO_HTTPS
#define IMAGE_COMBOOT
#define IMAGE_PNG
#define NET_PROTO_IPV6
#define PING_CMD
#define PXE_CMD
#define REBOOT_CMD
#define VLAN_CMD
